/* configuration.h -- Autogenerated file! Do not edit. */

#ifndef __ST_SENSOR_HAL_CONFIG_H
#define __ST_SENSOR_HAL_CONFIG_H

#define CONFIG_ST_HAL_HAS_SELFTEST_FUNCTIONS 1
#define CONFIG_ST_HAL_MIN_FUSION_POLLRATE 50

#endif /* __ST_SENSOR_HAL_CONFIG_H */
